export const ClientEvent = {
  CLAIM: 'CLAIM',
  CHALLENGE: 'CHALLENGE',
  START_GAME: 'START_GAME',
  START_ROUND: 'START_ROUND',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  REORDER_PLAYERS: 'REORDER_PLAYERS',
  RESET_GAME: 'RESET_GAME',
  LEAVE_GAME: 'LEAVE_GAME',
} as const;

export type ClientEventName = typeof ClientEvent[keyof typeof ClientEvent];

export const ServerEvent = {
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  PLAYER_FORFEIT: 'PLAYER_FORFEIT',
  GAME_STARTED: 'GAME_STARTED',
  ROUND_STARTED: 'ROUND_STARTED',
  DICE_ROLLED: 'DICE_ROLLED',
  CLAIM_MADE: 'CLAIM_MADE',
  CHALLENGE_MADE: 'CHALLENGE_MADE',
  GAME_ENDED: 'GAME_ENDED',
  GAME_STATE: 'GAME_STATE',
  GAME_RESET: 'GAME_RESET',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  PLAYERS_REORDERED: 'PLAYERS_REORDERED',
  ERROR: 'ERROR',
} as const;

export type ServerEventName = typeof ServerEvent[keyof typeof ServerEvent];
