export enum StateChange {
    PLAYER_JOINED = "PLAYER_JOINED",
    PLAYER_LEFT = "PLAYER_LEFT",
    GAME_STARTED = "GAME_STARTED",
    ROUND_STARTED = "ROUND_STARTED",
    DICE_ROLLED = "DICE_ROLLED",
    CLAIM_MADE = "CLAIM_MADE",
    CHALLENGE_MADE = "CHALLENGE_MADE",
    GAME_ENDED = "GAME_ENDED",
    GAME_STATE = "GAME_STATE"
}